### Numpy Arrays
Numpy is a general purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamenta package for scientific computing with python.

#### What is an array?

An array is a data structure that stores values of some data type, in Python, the main difference between arrays and lists is, while python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

In [1]:
## Import library to work with arrays, the library is called numpy
import numpy as np

In [4]:
lst = [1,2,3,4]
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [10]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1 =np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
arr1.shape

(3, 5)

In [16]:
arr[3]

4

In [17]:
arr[3] = 5

In [20]:
arr[1:]

array([2, 3, 5])

In [21]:
arr

array([1, 2, 3, 5])

In [29]:
# printing last item in arr
print(arr[-1])

# printing all items except last item : means all, so :-1 all minus 1...
print(arr[:-1])

# :: operator is used for slicing sequences. 
# It’s a way to access elements of a sequence such as a list, tuple, or string. 
# The syntax is sequence[start:stop:step].
print(arr[::-1])
print(arr[::-2])
print(arr[::2])


5
[1 2 3]
[5 3 2 1]
[5 2]
[1 3]


In [30]:
# Multidimensional indexing

arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [50]:
# : means all rows and 1 means second column
print(arr1[:,1])
# more complex
print(arr1[1:,1:3])
print(arr1[1:,3:])
print(arr1[:,3:])
print(arr1[:,::4])


[2 3 4]
[[3 4]
 [4 5]]
[[5 6]
 [6 7]]
[[4 5]
 [5 6]
 [6 7]]
[[1 5]
 [2 6]
 [3 7]]
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [51]:
# EDA
arr

array([1, 2, 3, 5])

In [54]:
print(arr<2)
print(arr[arr<2])

[ True False False False]
[1]


In [56]:
# Another way to create numpy arrays
print(arr1.shape)
print(arr1)

(3, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [58]:
# change shape (invert), the shape should match with the data
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [62]:
# .arange() arguments are (start,stop,step)
print(np.arange(1,10,1))
print(np.arange(1,20,2).reshape(2,5))

[1 2 3 4 5 6 7 8 9]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [66]:
# creating 3 dimensional array
# .reshape(1,10,1): This reshapes the array into a new form. 
# The arguments (1,10,1) specify the new shape: 1 for the depth (number of matrices), 10 for the number of rows in each matrix, and 1 for the number of columns in each row.
np.arange(1,20,2).reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [68]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [69]:
print(arr *arr)


[ 1  4  9 25]


In [70]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [72]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
# creates an array of zeros in the shape of existing arrays given in argument
np.zeros_like(arr)

array([0, 0, 0, 0])

In [79]:
# gives random numbers arguments (start, stop, size)
np.random.randint(10,50,4)

array([25, 23, 48, 22])

In [97]:
# create mutli dimensional array with randint()
# My way of seeing multidimensional arrays in .reshape argument: number of rows, number of items, number of culumns
np.random.randint(1,20,30).reshape(1,10,3)

array([[[ 7, 13, 11],
        [ 1, 16, 10],
        [13,  7, 19],
        [ 1,  7,  8],
        [ 1,  7, 16],
        [16, 13,  4],
        [ 9, 17, 15],
        [ 2,  6,  3],
        [19, 14, 10],
        [ 1, 10,  4]]])

In [109]:
# standard normal distribution
np.random.randn(2,3,2)

array([[[ 0.33529459,  0.26036534],
        [ 0.05261654, -0.85551324],
        [ 0.18676072, -0.15259026]],

       [[ 1.72516627, -1.00942668],
        [ 1.95782475,  0.69983454],
        [ 0.66715188,  0.61406692]]])

In [112]:
np.random.random_sample((2,3,2))

array([[[0.79590285, 0.04047807],
        [0.63751549, 0.44972567],
        [0.55526028, 0.22856173]],

       [[0.92957125, 0.51855983],
        [0.94693603, 0.64606387],
        [0.07417669, 0.26286784]]])